version: '3.3'

services:

  backdrop:
    build:
      context: ../path/to/docker/backdrop
      args:
        - COMPOSER_VERSION=latest
        - PHP_VERSION=7.1
        - DRUSH_VERSION=8.x
    links:
      - maildev
      - mariadb
    ports:
      - 80:80
    restart: always
    volumes:
      - ./src:/var/www/html

  mariadb:
    image: mariadb:10.2.9
    environment:
      - MYSQL_DATABASE=backdrop
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 3306:3306
    restart: always
    volumes:
      - ./var/data/mysql:/var/lib/mysql

  maildev:
    image: djfarrelly/maildev
    ports:
      - 1080:80
