version: '3.3'

services:

  drupal:
    build:
      context: ../docker/drupal7
      args:
        - COMPOSER_VERSION=latest
        - PHP_VERSION=7.1
        - DRUSH_VERSION=8.x
        - BUILD_DEV=1
    depends_on:
      - mariadb
    links:
      - maildev:mail
      - mariadb
    ports:
      - 80:80
    restart: always
    volumes:
      - ./src:/var/www/html:cached

  mariadb:
    image: mariadb:10.3
    environment:
      - MYSQL_DATABASE=drupal
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 3306:3306
    restart: always
    volumes:
      - ./var/data/mysql:/var/lib/mysql:consistent

  maildev:
    image: djfarrelly/maildev
    ports:
      - 8025:80
